name: Cache Prime da22e55

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Cache step
      id: cache-step
      uses: actions/cache@v4
      with:
        path: cache-folder
        key: cache-da22e55

    - name: Generate file if cache miss
      if: steps.cache-step.outputs.cache-hit != 'true'
      run: |
        mkdir cache-folder
        echo "cache test" > cache-folder/file.txt

    - name: prime-cache-da22e55
      run: echo "Cache hit ${{ steps.cache-step.outputs.cache-hit }}"
